name: footprint
description: Footprint. configurable log to console create footprints and report to crashlytics with ease
version: 1.1.3
homepage: https://github.com/easazade/footprint

environment:
  sdk: ">=2.7.0 <3.0.0"

  path_provider:
  path:

dependencies:

dev_dependencies:
  test: ^1.15.4

